### PR TITLE
Upgrade mkdirp for better compatability with newer TS versions

### PR DESCRIPTION
**Pull request by wvdemeer**
(code credit @twalcari)

### CODE REVIEW

**Comment by rubensworks** [comment]
@wvdemeer It looks like the CI fails due to a linter error, could you have a look?

**Comment by wvdemeer** [comment]
layout fixed to make the linter happy :smiley:

**Comment by rubensworks** [comment]
🚀 🚀 🚀

**Comment by rubensworks** [comment]
Released as 2.5.0.

**Pull request merged**
